name: docker-image-workflow
on:
  push:
    branches:
      -main
jobs:
  build:
    run-on: ubuntu-latest
    steps:
    - name: checkout code
      user: actions/checkout@v3

    - name: Build
      run:
        echo: "Docker build"
    - name: Tag Docker Image
      run:
      echo: "Docker push image"
    
